---
title: "p8105_hw3_xw2961"
output: github_document
date: "`Oct 16`"
---

#load packages
```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(readr)
library(ggplot2)
```

### Problem 2
```{r}
# dataset loading, tidy, merge
demographic = read_csv("./data/nhanes_covar.csv") %>%
  {colnames(.) <- as.character(.[4, ]); .} %>%  # Set 4th row as column names
  slice(-c(1:4)) %>%                            # Remove the first four rows
  janitor::clean_names() %>% 
  filter(age >= 21) %>%                        
  mutate(sex = recode(sex, "1" = "male", "2" = "female")) %>%  
  mutate(education = recode(education,         
                            "1" = "Less than high school", 
                            "2" = "High school equivalent", 
                            "3" = "More than high school")) %>% 
  drop_na() %>% 
  mutate(age = as.numeric(age)) %>% 
  mutate(bmi = as.numeric(bmi))
demographic
  


accelerometers = read_csv("./data/nhanes_accel.csv") %>% 
  janitor::clean_names() %>% 
  mutate(seqn=as.character(seqn))
accelerometers

merged_dataset = left_join(demographic, accelerometers, "seqn")
merged_dataset


# table for the number of men and women in each education category

education_gender_count <- merged_dataset %>%
  group_by(education, sex) %>%  # Group by education and sex
  summarise(count = n()) %>% # Count the number of occurrences in each group
  knitr::kable()

education_gender_count

# a visualization of the age distributions for men and women in each education category
ggplot(merged_dataset, aes(x = education,y = age, fill = sex)) +
  geom_violin(trim = FALSE, width = 1, alpha = 0.6) +  
  geom_jitter(aes(color = sex), width = 0.1, alpha = 0.6) +  
  facet_wrap(~ sex) +                                       
  labs(title = "Age Distribution by Education Level and Sex",
       x = "Education Level", y = "Age")+ 
  theme_minimal() +                                         
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  
      panel.grid.major = element_blank(),                 
      panel.grid.minor = element_blank())                 

# Combine to total activity
aggregate_dataset = merged_dataset %>%
  mutate(total_activity_min = rowSums(select(., "min1":"min1440")))

# Plot total activities against age
total_activity_scatter_plot = 
  aggregate_dataset %>%  
  ggplot(aes(x = age, y = total_activity_min, color = sex)) + 
  geom_point()+
  ggtitle("Scatterplot of Age against Total Physical Activity in Minutes") + 
  xlab("Age") + 
  ylab("Total Minutes")+
  geom_smooth()+
  facet_grid( . ~ education )

total_activity_scatter_plot

# Plot 24-hour activity time courses for each education level 
merged_dataset %>%
  group_by(sex, education) %>% 
  summarise(across(starts_with("min"), mean, na.rm = TRUE)) %>%
  pivot_longer(cols = starts_with("min"), names_to = "minute", values_to = "mean_activity") %>%
  ggplot(aes(x = minute, y = mean_activity, color = sex)) +
  geom_point(alpha = 0.3) + 
  geom_line() +
  geom_smooth(se = FALSE) +
  ggtitle("24-Hour Activity Time Course by Education Level") +
  facet_grid(. ~ education) 
```


### Question 3
```{r}
# Importing datasets
Jan_2020 = 
  read_csv("./data/Jan 2020 Citi.csv") %>% 
  janitor::clean_names()

Jul_2020 = 
  read_csv("./data/July 2020 Citi.csv") %>% 
  janitor::clean_names()

Jan_2024 = 
  read_csv("./data/Jan 2024 Citi.csv") %>% 
  janitor::clean_names()

Jul_2024 = 
  read_csv("./data/July 2024 Citi.csv") %>% 
  janitor::clean_names()

# Combining and cleaning datasets
combined_data <- bind_rows(
  Jan_2020 %>% mutate(period = "Jan_2020"),
  Jul_2020 %>% mutate(period = "Jul_2020"),
  Jan_2024 %>% mutate(period = "Jan_2024"),
  Jul_2024 %>% mutate(period = "Jul_2024")
)
combined_data

# creating the table for membership and time
rides_table <- combined_data %>%
  group_by(period, member_casual) %>%  
  summarise(count = n()) %>% 
  knitr::kable()

rides_table

#creating the table for the 5 most popular starting stations for July 2024
top_stations_july_2024 <- combined_data %>%
  filter(period == "Jul_2024") %>% 
  group_by(start_station_name) %>% 
  summarise(total_rides = n(), .groups = "drop") %>%  
  arrange(desc(total_rides)) %>%  
  slice_head(n = 5)  

knitr::kable(top_stations_july_2024)


#creating the plot about median ride duration
plot_data <- combined_data %>%
  separate(period, into = c("month", "year"), sep = "_") %>%
  mutate(weekdays = factor(weekdays, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))) %>%
  group_by(weekdays, month, year) %>% 
  summarise(median_duration = median(duration, na.rm = TRUE), .groups = "drop") %>% 
  ggplot(aes(x = weekdays, y = median_duration, color = year)) +
  geom_line(aes(group = year)) +
  facet_grid(. ~ month) +
  labs(
    title = "Effects of Day of the Week, Month, and Year on Median Ride Duration",
    x = "Day of the Week",
    y = "Median Ride Duration (minutes)") +
    theme(axis.text.x = element_text(angle = 45))

  
plot_data

#creating the plot about data in 2024
plot_data_2024 <- combined_data %>% 
  separate(period, into = c("month", "year"), sep = "_") %>%
  filter(year == "2024") %>% 
  group_by(month,member_casual,rideable_type) %>% 
  ggplot(aes(x = duration, fill = member_casual))+
  geom_density(alpha=0.5)+
  facet_grid(month~rideable_type)+
  labs(
    title = "Effects of Month,Membership Status,Bike Type on the Distribution of Ride Duration",
    x = "Duration of Ride",
    y = "density")
plot_data_2024

```


